import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#c7eccf",
        "herbal-beige": "#E8D8BD",
        "tertiary-fixed-dim": "#ffb692",
        "surface-variant": "#e8e2d6",
        "on-surface": "#1d1c14",
        "soft-sage": "#A8BFA3",
        "on-error-container": "#93000a",
        "text-main": "#2B2B2B",
        "primary-fixed-dim": "#acd0ad",
        "secondary-fixed-dim": "#abcfb4",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#2e4d39",
        "on-secondary-container": "#4b6c55",
        "surface-container-high": "#ede8dc",
        "inverse-surface": "#333028",
        "error-text": "#B94A3A",
        "surface-container-low": "#f9f3e7",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#2f4e33",
        "primary-fixed": "#c8ecc8",
        "surface-dim": "#dfd9ce",
        "on-primary-fixed": "#03210b",
        "on-tertiary-fixed": "#341100",
        "surface-bright": "#fff9ed",
        "on-tertiary-fixed-variant": "#733510",
        "surface-container": "#f3ede1",
        "on-primary-container": "#ccf0cc",
        "tertiary": "#7e3d18",
        "tertiary-fixed": "#ffdbcb",
        "secondary": "#45664f",
        "on-background": "#1d1c14",
        "on-tertiary-container": "#ffe1d3",
        "border-warm": "#DDD0BC",
        "on-secondary": "#ffffff",
        "text-muted": "#6F6A61",
        "outline": "#737971",
        "on-secondary-fixed": "#012110",
        "on-tertiary": "#ffffff",
        "background": "#fff9ed",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#424841",
        "success-bg": "#E7F0E4",
        "surface": "#fff9ed",
        "surface-tint": "#466649",
        "tertiary-container": "#9c542d",
        "surface-container-highest": "#e8e2d6",
        "primary": "#37563b",
        "earth-brown": "#8A6A4F",
        "outline-variant": "#c2c8bf",
        "error-bg": "#FBEAE5",
        "primary-container": "#4f6f52",
        "secondary-container": "#c7eccf",
        "inverse-on-surface": "#f6f0e4",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#acd0ad",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "sm": "16px",
        "xs": "8px",
        "base": "4px",
        "md": "24px",
        "lg": "48px",
        "gutter": "40px",
        "container-max": "1920px",
        "xl": "80px",
      },
      maxWidth: {
        "xs": "20rem",
        "sm": "24rem",
        "md": "28rem",
        "lg": "32rem",
        "xl": "36rem",
        "container-max": "1920px",
      },
      fontFamily: {
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "display-lg-mobile": ["var(--font-merriweather)", "serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-merriweather)", "serif"],
        "price-display": ["var(--font-inter)", "sans-serif"],
        "display-lg": ["var(--font-merriweather)", "serif"],
        "caption": ["var(--font-inter)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-merriweather)", "serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.7", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-md": ["15px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.35", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "1.3", fontWeight: "600" }],
        "price-display": ["28px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["56px", { lineHeight: "1.2", fontWeight: "700" }],
        "caption": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "headline-lg-mobile": ["26px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
