-- =============================================================
-- NaHerbs Supabase PostgreSQL Seed v1
-- File: 002_seed_minimal.sql
-- Usage: Run after 001_init_schema.sql.
-- =============================================================

set search_path = naherb, public, extensions;

-- Site settings
insert into naherb.site_settings (setting_key, setting_value, value_type, description)
values
  ('brand_name', 'NaHerbs', 'TEXT', 'Tên thương hiệu'),
  ('hotline', '', 'TEXT', 'Hotline hiển thị trên website'),
  ('zalo_url', '', 'TEXT', 'Link Zalo'),
  ('facebook_url', '', 'TEXT', 'Link Facebook'),
  ('email', '', 'TEXT', 'Email liên hệ'),
  ('address', '', 'TEXT', 'Địa chỉ'),
  ('default_disclaimer', 'Sản phẩm thảo dược hỗ trợ thư giãn và chăm sóc sức khỏe tại nhà, không thay thế thuốc hoặc chỉ định của bác sĩ. Nếu tình trạng đau kéo dài hoặc có dấu hiệu bất thường, bạn nên thăm khám tại cơ sở y tế.', 'TEXT', 'Disclaimer sức khỏe mặc định'),
  ('bank_name', '', 'TEXT', 'Tên ngân hàng nhận chuyển khoản QR'),
  ('bank_account_number', '', 'TEXT', 'Số tài khoản nhận chuyển khoản QR'),
  ('bank_account_name', '', 'TEXT', 'Chủ tài khoản nhận chuyển khoản QR'),
  ('bank_qr_url', '', 'TEXT', 'URL ảnh QR cố định')
on conflict (setting_key) do nothing;

-- Chatbot config
insert into naherb.chatbot_configs (
  enabled,
  welcome_message,
  fallback_message,
  disclaimer,
  system_prompt,
  suggested_questions,
  max_products_per_answer
)
select
  true,
  'Xin chào, NaHerbs có thể giúp bạn chọn sản phẩm thảo dược phù hợp. Bạn đang cần thư giãn vùng cổ vai gáy, lưng, mắt, xông ngải hay tinh dầu?',
  'Mình chưa đủ thông tin để tư vấn chính xác. Bạn có thể để lại số điện thoại/Zalo hoặc liên hệ hotline để NaHerbs hỗ trợ trực tiếp.',
  'Thông tin chỉ mang tính tham khảo, không thay thế tư vấn y tế.',
  'Bạn là trợ lý tư vấn sản phẩm cho website NaHerbs. Chỉ tư vấn dựa trên sản phẩm và bài viết được cung cấp trong context. Không tự tạo sản phẩm, giá, tồn kho, biến thể hoặc công dụng không có trong context. Không chẩn đoán bệnh, không cam kết chữa khỏi, không thay thế bác sĩ hoặc thuốc. Ưu tiên sản phẩm còn hàng và trả lời ngắn gọn bằng tiếng Việt.',
  '["Tôi bị mỏi cổ vai gáy nên dùng sản phẩm nào?", "Tôi ngồi văn phòng nhiều nên chọn gối hay túi chườm?", "Tôi muốn mua quà tặng sức khỏe cho người lớn tuổi", "Tôi bị mỏi mắt do dùng máy tính nhiều", "Tôi muốn tìm sản phẩm xông ngải cứu tại nhà", "Tôi muốn tinh dầu để thư giãn không gian phòng"]'::jsonb,
  3
where not exists (select 1 from naherb.chatbot_configs);

-- Product categories
insert into naherb.product_categories (name, slug, description, status, display_order)
values
  ('Gối & cổ vai gáy', 'goi-co-vai-gay', 'Gối và sản phẩm hỗ trợ thư giãn vùng cổ vai gáy.', 'PUBLISHED', 1),
  ('Túi/gối chườm thảo dược', 'tui-goi-chuom-thao-duoc', 'Sản phẩm chườm nóng/thảo dược cho lưng, bụng, vai gáy.', 'PUBLISHED', 2),
  ('Xông ngải cứu', 'xong-ngai-cuu', 'Cốc xông, bộ xông và điếu ngải cứu.', 'PUBLISHED', 3),
  ('Tinh dầu thiên nhiên', 'tinh-dau-thien-nhien', 'Tinh dầu thảo dược cho không gian thư giãn.', 'PUBLISHED', 4),
  ('Phụ kiện thư giãn/du lịch', 'phu-kien-thu-gian-du-lich', 'Gối chữ U, bịt mắt và sản phẩm tiện mang theo.', 'PUBLISHED', 5),
  ('Quà tặng sức khỏe', 'qua-tang-suc-khoe', 'Nhóm sản phẩm phù hợp làm quà tặng sức khỏe.', 'PUBLISHED', 6)
on conflict (slug) do nothing;

-- Blog categories
insert into naherb.blog_categories (name, slug, description, status)
values
  ('Chăm sóc cổ vai gáy', 'cham-soc-co-vai-gay', 'Bài viết về thư giãn cổ vai gáy.', 'PUBLISHED'),
  ('Chườm nóng & thảo dược', 'chuom-nong-thao-duoc', 'Hướng dẫn chườm nóng và dùng thảo dược an toàn.', 'PUBLISHED'),
  ('Xông ngải cứu', 'xong-ngai-cuu', 'Kiến thức sử dụng ngải cứu trong chăm sóc tại nhà.', 'PUBLISHED'),
  ('Tinh dầu & thư giãn', 'tinh-dau-thu-gian', 'Bài viết về tinh dầu và không gian thư giãn.', 'PUBLISHED')
on conflict (slug) do nothing;

-- Dev admin placeholder.
-- Replace password_hash with a BCrypt hash generated by naherb-api.
-- Example only: do not use this value in production.
insert into naherb.admin_users (email, password_hash, full_name, status)
values ('admin@naherbs.local', '$2a$10$REPLACE_WITH_REAL_BCRYPT_HASH', 'NaHerbs Admin', 'ACTIVE')
on conflict (email) do nothing;
